services:
  blog-nuxt:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    # env_file:
    #   - ../.env

  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blog-nuxt